# C-b is awkward use C-a like screen
set-option -g prefix C-a
# C-a C-a goto last window
bind-key C-a last-window
# Allow C-a a to send a C-a to the window
bind-key a send-prefix

# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1

# Nicer resizing...
setw -g aggressive-resize on

#if-shell "[[ $(tmux -V | cut -d' ' -f2) -gt 2.0 ]]" "set -s focus-events on"
set -s focus-events on

# Give a very large history limit
set-option -g history-limit 100000

set -sg repeat-time 250
set -g automatic-rename on
set -g renumber-windows on

set -g set-titles on
#set -g monitor-activity on

# act like vim
set -gw mode-keys vi
set -g status-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

set -g default-terminal "tmux-256color"

# easy to remember window split keys
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g status-right "%I:%M%P #h"
# set status-right "%I:%M%P #h #(tmux list-panes -F '#{pane_active} #{pane_pid}' | grep '^1' | cut -f 2 -d ' ' | xargs pwdx | cut -f '2-' -d' ')"
# set status-right-length 60
# set status-interval 1


#if-shell "tmux show -g mouse 2>/dev/null" "set -g mouse on" "set -g mouse-resize-pane on; set -g mouse-select-pane on; set -g mouse-select-window on"
set -g mouse on

# Allow tmux and other applications to interact with the clipboard
set -g set-clipboard on
# Used to be default but off by default in 3.5
set -g allow-passthrough on
# the following where the defaults but are also needed for clipboard support
# bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
# bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Add these to update-environment to make sessions work nicer
set -ga update-environment "DBUS_SESSION_BUS_ADDRESS"
set -ga update-environment "XDG_SESSION_ID"

#### COLOUR (Solarized dark)

# default statusbar colors
#set-option -g status-bg black #base02
#set-option -g status-fg yellow #yellow
#set-option -g status-attr default
set-option -g status-style "bg=black,fg=yellow"

# default window title colors
#set-window-option -g window-status-fg brightblue #base0
#set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim
set-option -gw window-status-style "fg=brightblue,bg=default"

# active window title colors
#set-window-option -g window-status-current-fg brightred #orange
#set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright
set-option -gw window-status-current-style "fg=brightred,bg=default"

# pane border
#set-option -g pane-border-fg black #base02
set-option -g pane-border-style "fg=black"
#set-option -g pane-active-border-fg brightgreen #base01
set-option -g pane-active-border-style "fg=brightgreen"

# message text
#set-option -g message-bg black #base02
#set-option -g message-fg brightred #orange
set-option -g message-style "bg=black,fg=brightred"

# pane number display
set-option -g display-panes-active-colour blue #blue
set-option -g display-panes-colour brightred #orange

# clock
set-option -gw clock-mode-colour green #green

